; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CFSDlg
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "FS.h"

ClassCount=2
Class1=CFSApp
Class2=CFSDlg

ResourceCount=3
Resource2=IDD_FS_DIALOG (English (U.S.))
Resource1=IDR_MAINFRAME
Resource3=IDD_FS_DIALOG

[CLS:CFSApp]
Type=0
HeaderFile=FS.h
ImplementationFile=FS.cpp
Filter=N

[CLS:CFSDlg]
Type=0
HeaderFile=FSDlg.h
ImplementationFile=FSDlg.cpp
Filter=D
LastObject=CFSDlg
BaseClass=CDialog
VirtualFilter=dWC



[DLG:IDD_FS_DIALOG]
Type=1
Class=CFSDlg
ControlCount=10
Control1=IDC_SPLIT_RADIO,button,1342308361
Control2=IDC_MERGE_RADIO,button,1342177289
Control3=IDC_STATIC,static,1342308352
Control4=IDC_STATIC,static,1342308352
Control5=IDC_FILESELECT_EDIT,edit,1350631552
Control6=IDC_SELECTFILE_BUTTON,button,1342242816
Control7=IDC_STATIC,static,1342308352
Control8=IDC_BLOCKSIZE_EDIT,edit,1350631552
Control9=IDC_START_BUTTON,button,1342177281
Control10=IDC_PROGRESS,msctls_progress32,1350565888

[DLG:IDD_FS_DIALOG (English (U.S.))]
Type=1
ControlCount=10
Control1=IDC_SPLIT_RADIO,button,1342308361
Control2=IDC_MERGE_RADIO,button,1342177289
Control3=IDC_STATIC,static,1342308352
Control4=IDC_STATIC,static,1342308352
Control5=IDC_FILESELECT_EDIT,edit,1350631552
Control6=IDC_SELECTFILE_BUTTON,button,1342242816
Control7=IDC_STATIC,static,1342308352
Control8=IDC_BLOCKSIZE_EDIT,edit,1350631552
Control9=IDC_START_BUTTON,button,1342242816
Control10=IDC_PROGRESS,msctls_progress32,1350565888

