//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FS.rc
//
#define IDD_FS_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDC_SPLIT_RADIO                 1000
#define IDC_MERGE_RADIO                 1001
#define IDC_FILESELECT_EDIT             1002
#define IDC_SELECTFILE_BUTTON           1003
#define IDC_BLOCKSIZE_EDIT              1004
#define IDC_SPIN                        1005
#define IDC_START_BUTTON                1006
#define IDC_PROGRESS                    1007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
