//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by AC_FTP.RC
//
#define AC_FTP                          101
#define IDD_SERVER                      103
#define IDD_ABOUT                       104
#define IDD_OPTIONS                     105
#define IDC_CONNECT                     1000
#define IDC_STOR                        1001
#define IDC_RETR                        1008
#define IDC_CLOSE                       1009
#define IDABOUT                         1010
#define IDC_LCWD                        1017
#define IDC_LDEL                        1019
#define IDC_LDIR                        1020
#define IDC_RCWD                        1021
#define IDC_RDEL                        1022
#define IDC_RDIR                        1023
#define IDC_LPWD                        1024
#define IDC_RPWD                        1025
#define IDC_ABOR                        1026
#define IDC_REPLY                       1027
#define IDC_SERVER                      1028
#define IDC_TO_NUL                      1030
#define IDC_USERNAME                    1032
#define IDC_PASSWORD                    1033
#define IDC_DATA_RATE                   1035
#define IDC_EXIT                        1038
#define IDC_IOBEEP                      1039
#define IDC_OPTIONS                     1041
#define IDC_FROM_NUL                    1043
#define IDC_LOGFILE                     1044
#define IDC_REASYNC                     1045
#define IDC_STATUS                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
