; CLW file contains information for the MFC ClassWizard

[General Info]
Version=1
LastClass=CFilterDlg
LastTemplate=CDialog
NewFileInclude1=#include "stdafx.h"
NewFileInclude2=#include "Filter.h"

ClassCount=3
Class1=CFilterApp
Class2=CFilterDlg
Class3=CAboutDlg

ResourceCount=3
Resource1=IDD_ABOUTBOX
Resource2=IDR_MAINFRAME
Resource3=IDD_FILTER_DIALOG

[CLS:CFilterApp]
Type=0
HeaderFile=Filter.h
ImplementationFile=Filter.cpp
Filter=N

[CLS:CFilterDlg]
Type=0
HeaderFile=FilterDlg.h
ImplementationFile=FilterDlg.cpp
Filter=D
BaseClass=CDialog
VirtualFilter=dWC
LastObject=IDC_STATIC1

[CLS:CAboutDlg]
Type=0
HeaderFile=FilterDlg.h
ImplementationFile=FilterDlg.cpp
Filter=D

[DLG:IDD_ABOUTBOX]
Type=1
Class=CAboutDlg
ControlCount=4
Control1=IDC_STATIC,static,1342177283
Control2=IDC_STATIC,static,1342308480
Control3=IDC_STATIC,static,1342308352
Control4=IDOK,button,1342373889

[DLG:IDD_FILTER_DIALOG]
Type=1
Class=CFilterDlg
ControlCount=17
Control1=IDOK,button,1342242817
Control2=IDC_WAV1,button,1342242816
Control3=IDC_EDIT1,edit,1350639744
Control4=IDC_SPIN1,msctls_updown32,1342177334
Control5=IDC_STATIC1,button,1342177287
Control6=IDC_WAV3,button,1342242816
Control7=IDC_WAV4,button,1342242816
Control8=IDC_STATIC2,button,1342177287
Control9=IDC_STATIC,static,1342308352
Control10=IDC_WAV2,button,1342242816
Control11=IDC_EDIT2,edit,1350639744
Control12=IDC_SPIN2,msctls_updown32,1342177334
Control13=IDC_EDIT3,edit,1350639744
Control14=IDC_SPIN3,msctls_updown32,1342177334
Control15=IDC_STATIC3,button,1342177287
Control16=IDC_STATIC,static,1342308352
Control17=IDC_STATIC,static,1342308352

