//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Filter.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FILTER_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDC_WAV1                        1000
#define IDC_EDIT1                       1001
#define IDC_SPIN1                       1003
#define IDC_WAV3                        1005
#define IDC_WAV4                        1006
#define IDC_STATIC2                     1007
#define IDC_STATIC1                     1008
#define IDC_WAV2                        1009
#define IDC_EDIT2                       1010
#define IDC_SPIN2                       1011
#define IDC_EDIT3                       1012
#define IDC_SPIN3                       1013
#define IDC_STATIC3                     1014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
